[package]
name = "soldier"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daemonize = "0.4.1"
simplelog = "0.10.0"
log = "0.4.14"
walkietalkie = {path = ".."}